runtime: nodejs16
env: standard

handlers:
  - url: /
    static_files: index.html
    upload: index.html

  - url: /(.*)
    static_files: \1
    upload: (.*)

env_variables:
  NODE_ENV: "production"